---
title: "resolution"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{resolution}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(obisindicators)
library(dplyr)
library(dggridR) # remotes::install_github("r-barnes/dggridR")
library(sf)
```

```{r }
# these are WKT geometries that can be used to query OBIS
CA_BOX = "POLYGON ((
  -122 32,
  -122 42,
  -117 42,
  -117 32,
  -122 32
))"
CA_POLYGON = "POLYGON ((-121.9482421875 35.33529320309328, -120.47607421874999 33.284619968887675, -118.7841796875 32.41706632846282, -116.74072265625 32.63937487360669, -117.46582031249999 33.815666308702774, -119.28955078124999 34.72355492704221, -120.60791015625 35.35321610123823, -121.9482421875 35.33529320309328))"

# query OBIS for occurrence records
occ <- robis::occurrence(
#  c(
#    "Mytilus", "Anthopleura", "Chthamalus", "Balanus", "Silvetia",
#    "Pisaster", "Pollicipes", "Endocladia", "Phyllospadix"
#    ),
  geometry = CA_POLYGON,
  fields = c("decimalLongitude", "decimalLatitude", "species", "date_year", "aphiaID")
  # TODO: figure out how to exclude species=NA records
)

# squish the data down into the shape expected by metric calculating code
occ <- group_by(
  occ, decimalLongitude, decimalLatitude, species, date_year) %>%  # remove dulplicate rows
  filter(!is.na(species))  %>%
  summarize(
    records = n(),
    .groups = "drop") %>%
  collect()
```

## Create function to make grid, calculate metrics for different resolution grid sizes

```{r function}
res_changes <- function(resolution = 9){
    dggs <- dgconstruct(projection = "ISEA", topology = "HEXAGON", res = resolution)
    occ$cell <- dgGEO_to_SEQNUM(dggs, occ$decimalLongitude, occ$decimalLatitude)[["seqnum"]]
    idx <- calc_indicators(occ)

  grid <- dgcellstogrid(dggs, idx$cell) %>%
    st_wrap_dateline() %>%
    rename(cell = seqnum) %>%
    left_join(
      idx,
      by = "cell")
  return(grid)
}
```

## plot stuff
```{r}
grid <- res_changes(11)
gmap_indicator(grid, "es", label = "ES(50)")
gmap_indicator(grid, "n", label = "# records")
```
